# Generated by Django 5.0.6 on 2024-09-12 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vid', models.AutoField(primary_key=True, serialize=False)),
                ('vname', models.CharField(max_length=255)),
                ('phno', models.CharField(max_length=10)),
                ('GSTNO', models.CharField(max_length=15)),
                ('Address', models.TextField()),
            ],
            options={
                'db_table': 'Vendor',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=255)),
                ('Type', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Qty', models.IntegerField()),
                ('vid', models.ForeignKey(db_column='vid', on_delete=django.db.models.deletion.CASCADE, to='mykac.vendor')),
            ],
            options={
                'db_table': 'Stock',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('Qty', models.IntegerField()),
                ('sid', models.ForeignKey(db_column='sid', on_delete=django.db.models.deletion.CASCADE, to='mykac.stock')),
                ('vid', models.ForeignKey(db_column='vid', on_delete=django.db.models.deletion.CASCADE, to='mykac.vendor')),
            ],
            options={
                'db_table': 'Order',
            },
        ),
    ]
